<?php
/** Generic CRUD module definitions. Field types:
 *  text, textarea, richtext, slug, select, number, date, checkbox, image, video, fk
 */
function admin_modules(): array
{
    return [
        'doctors' => [
            'label' => 'Doctors', 'table' => 'doctors', 'permission' => 'doctors.manage',
            'title_field' => 'name', 'order' => 'position, id', 'search' => ['name', 'designation', 'specialisation'],
            'columns' => ['name', 'designation', 'specialisation', 'status'],
            'fields' => [
                ['name'=>'name','label'=>'Name','type'=>'text','required'=>true],
                ['name'=>'slug','label'=>'URL Slug','type'=>'slug','from'=>'name'],
                ['name'=>'designation','label'=>'Designation','type'=>'text'],
                ['name'=>'qualifications','label'=>'Qualifications','type'=>'text'],
                ['name'=>'specialisation','label'=>'Specialisation','type'=>'text'],
                ['name'=>'photo','label'=>'Portrait Photo','type'=>'image'],
                ['name'=>'biography','label'=>'Biography','type'=>'textarea'],
                ['name'=>'education','label'=>'Education & Training','type'=>'textarea'],
                ['name'=>'expertise','label'=>'Clinical Expertise','type'=>'textarea'],
                ['name'=>'fellowships','label'=>'Fellowships (verified only)','type'=>'textarea'],
                ['name'=>'memberships','label'=>'Memberships (verified only)','type'=>'textarea'],
                ['name'=>'awards_text','label'=>'Awards (verified only)','type'=>'textarea'],
                ['name'=>'is_featured','label'=>'Featured on homepage','type'=>'checkbox'],
                ['name'=>'status','label'=>'Status','type'=>'select','options'=>['draft'=>'Draft','published'=>'Published']],
                ['name'=>'position','label'=>'Display Order','type'=>'number'],
            ],
        ],
        'specialities' => [
            'label' => 'Specialities', 'table' => 'specialities', 'permission' => 'specialities.manage',
            'title_field' => 'name', 'order' => 'position, id', 'search' => ['name', 'category'],
            'columns' => ['name', 'category', 'status'],
            'fields' => [
                ['name'=>'name','label'=>'Name','type'=>'text','required'=>true],
                ['name'=>'slug','label'=>'URL Slug','type'=>'slug','from'=>'name'],
                ['name'=>'category','label'=>'Category','type'=>'text'],
                ['name'=>'short_description','label'=>'Short Description','type'=>'textarea'],
                ['name'=>'image','label'=>'Image','type'=>'image'],
                ['name'=>'overview','label'=>'Overview','type'=>'textarea'],
                ['name'=>'symptoms','label'=>'Symptoms','type'=>'textarea'],
                ['name'=>'conditions','label'=>'Conditions Managed','type'=>'textarea'],
                ['name'=>'diagnostics','label'=>'Diagnostic Evaluation','type'=>'textarea'],
                ['name'=>'treatments_text','label'=>'Treatment Options','type'=>'textarea'],
                ['name'=>'technology_text','label'=>'Technology','type'=>'textarea'],
                ['name'=>'what_to_expect','label'=>'What to Expect','type'=>'textarea'],
                ['name'=>'recovery','label'=>'Recovery & Follow-Up','type'=>'textarea'],
                ['name'=>'is_featured','label'=>'Featured on homepage','type'=>'checkbox'],
                ['name'=>'status','label'=>'Status','type'=>'select','options'=>['draft'=>'Draft','published'=>'Published']],
                ['name'=>'position','label'=>'Display Order','type'=>'number'],
            ],
        ],
        'treatments' => [
            'label' => 'Treatments', 'table' => 'treatments', 'permission' => 'specialities.manage',
            'title_field' => 'name', 'order' => 'position, id', 'search' => ['name'],
            'columns' => ['name', 'status'],
            'fields' => [
                ['name'=>'name','label'=>'Name','type'=>'text','required'=>true],
                ['name'=>'slug','label'=>'URL Slug','type'=>'slug','from'=>'name'],
                ['name'=>'speciality_id','label'=>'Speciality','type'=>'fk','fk_table'=>'specialities','fk_label'=>'name'],
                ['name'=>'short_description','label'=>'Short Description','type'=>'textarea'],
                ['name'=>'image','label'=>'Image','type'=>'image'],
                ['name'=>'overview','label'=>'Overview','type'=>'textarea'],
                ['name'=>'procedure_text','label'=>'How It Is Performed','type'=>'textarea'],
                ['name'=>'benefits','label'=>'Benefits','type'=>'textarea'],
                ['name'=>'recovery','label'=>'Recovery & After-Care','type'=>'textarea'],
                ['name'=>'status','label'=>'Status','type'=>'select','options'=>['draft'=>'Draft','published'=>'Published']],
                ['name'=>'position','label'=>'Display Order','type'=>'number'],
            ],
        ],
        'technologies' => [
            'label' => 'Technology', 'table' => 'technologies', 'permission' => 'content.manage',
            'title_field' => 'name', 'order' => 'position, id', 'search' => ['name'],
            'columns' => ['name', 'category', 'status'],
            'fields' => [
                ['name'=>'name','label'=>'Name','type'=>'text','required'=>true],
                ['name'=>'slug','label'=>'URL Slug','type'=>'slug','from'=>'name'],
                ['name'=>'category','label'=>'Category','type'=>'select','options'=>['diagnostics'=>'Diagnostics','laser'=>'Laser','surgical'=>'Surgical','facility'=>'Facility']],
                ['name'=>'short_description','label'=>'Short Description','type'=>'textarea'],
                ['name'=>'description','label'=>'Full Description','type'=>'textarea'],
                ['name'=>'image','label'=>'Image','type'=>'image'],
                ['name'=>'status','label'=>'Status','type'=>'select','options'=>['draft'=>'Draft','published'=>'Published']],
                ['name'=>'position','label'=>'Display Order','type'=>'number'],
            ],
        ],
        'blog_posts' => [
            'label' => 'Blog Posts', 'table' => 'blog_posts', 'permission' => 'content.manage',
            'title_field' => 'title', 'order' => 'id DESC', 'search' => ['title'],
            'columns' => ['title', 'status', 'published_at'],
            'fields' => [
                ['name'=>'title','label'=>'Title','type'=>'text','required'=>true],
                ['name'=>'slug','label'=>'URL Slug','type'=>'slug','from'=>'title'],
                ['name'=>'category_id','label'=>'Category','type'=>'fk','fk_table'=>'blog_categories','fk_label'=>'name'],
                ['name'=>'excerpt','label'=>'Excerpt','type'=>'textarea'],
                ['name'=>'content','label'=>'Content (HTML allowed)','type'=>'richtext'],
                ['name'=>'featured_image','label'=>'Featured Image','type'=>'image'],
                ['name'=>'medical_reviewer','label'=>'Medical Reviewer','type'=>'text'],
                ['name'=>'is_featured','label'=>'Featured','type'=>'checkbox'],
                ['name'=>'status','label'=>'Status','type'=>'select','options'=>['draft'=>'Draft','review'=>'In Review','published'=>'Published']],
                ['name'=>'published_at','label'=>'Publish Date','type'=>'datetime'],
            ],
        ],
        'blog_categories' => [
            'label' => 'Blog Categories', 'table' => 'blog_categories', 'permission' => 'content.manage',
            'title_field' => 'name', 'order' => 'position, id', 'search' => ['name'],
            'columns' => ['name', 'slug'],
            'fields' => [
                ['name'=>'name','label'=>'Name','type'=>'text','required'=>true],
                ['name'=>'slug','label'=>'URL Slug','type'=>'slug','from'=>'name'],
                ['name'=>'description','label'=>'Description','type'=>'textarea'],
                ['name'=>'position','label'=>'Display Order','type'=>'number'],
            ],
        ],
        'faqs' => [
            'label' => 'FAQs', 'table' => 'faqs', 'permission' => 'content.manage',
            'title_field' => 'question', 'order' => 'position, id', 'search' => ['question', 'answer'],
            'columns' => ['question', 'category', 'is_active'],
            'fields' => [
                ['name'=>'question','label'=>'Question','type'=>'text','required'=>true],
                ['name'=>'answer','label'=>'Answer (medically responsible)','type'=>'textarea','required'=>true],
                ['name'=>'category','label'=>'Category','type'=>'text'],
                ['name'=>'context','label'=>'Context (website / speciality slug)','type'=>'text'],
                ['name'=>'is_active','label'=>'Active','type'=>'checkbox'],
                ['name'=>'position','label'=>'Display Order','type'=>'number'],
            ],
        ],
        'testimonials' => [
            'label' => 'Testimonials', 'table' => 'testimonials', 'permission' => 'content.manage',
            'title_field' => 'patient_name', 'order' => 'position, id', 'search' => ['patient_name', 'content'],
            'columns' => ['patient_name', 'context', 'status'],
            'fields' => [
                ['name'=>'patient_name','label'=>'Patient Name','type'=>'text','required'=>true],
                ['name'=>'context','label'=>'Context (e.g. Cataract Surgery)','type'=>'text'],
                ['name'=>'content','label'=>'Testimonial (genuine, approved only)','type'=>'textarea','required'=>true],
                ['name'=>'status','label'=>'Status','type'=>'select','options'=>['draft'=>'Draft','published'=>'Published']],
                ['name'=>'position','label'=>'Display Order','type'=>'number'],
            ],
        ],
        'gallery_items' => [
            'label' => 'Gallery', 'table' => 'gallery_items', 'permission' => 'content.manage',
            'title_field' => 'title', 'order' => 'category, position', 'search' => ['title', 'caption'],
            'columns' => ['title', 'category', 'is_active'],
            'fields' => [
                ['name'=>'title','label'=>'Title','type'=>'text'],
                ['name'=>'category','label'=>'Category','type'=>'select','options'=>['infrastructure'=>'Infrastructure','doctors'=>'Doctors','technology'=>'Technology','events'=>'Events','community'=>'Community','media'=>'Media']],
                ['name'=>'image','label'=>'Image','type'=>'image','required'=>true],
                ['name'=>'caption','label'=>'Caption / Alt Text','type'=>'text'],
                ['name'=>'is_active','label'=>'Active','type'=>'checkbox'],
                ['name'=>'position','label'=>'Display Order','type'=>'number'],
            ],
        ],
        'reels' => [
            'label' => 'Reels & Videos', 'table' => 'reels', 'permission' => 'content.manage',
            'title_field' => 'title', 'order' => 'position, id', 'search' => ['title'],
            'columns' => ['title', 'category', 'status'],
            'fields' => [
                ['name'=>'title','label'=>'Title','type'=>'text','required'=>true],
                ['name'=>'description','label'=>'Description','type'=>'textarea'],
                ['name'=>'doctor_id','label'=>'Associated Doctor','type'=>'fk','fk_table'=>'doctors','fk_label'=>'name'],
                ['name'=>'category','label'=>'Category','type'=>'text'],
                ['name'=>'video_path','label'=>'Video (MP4, 9:16)','type'=>'video'],
                ['name'=>'thumbnail','label'=>'Thumbnail / Poster','type'=>'image'],
                ['name'=>'position','label'=>'Display Order','type'=>'number'],
                ['name'=>'status','label'=>'Status','type'=>'select','options'=>['draft'=>'Draft','published'=>'Published']],
            ],
        ],
        'media_items' => [
            'label' => 'Media & News', 'table' => 'media_items', 'permission' => 'content.manage',
            'title_field' => 'title', 'order' => 'published_at DESC, id DESC', 'search' => ['title'],
            'columns' => ['title', 'type', 'status', 'published_at'],
            'fields' => [
                ['name'=>'title','label'=>'Title','type'=>'text','required'=>true],
                ['name'=>'type','label'=>'Type','type'=>'select','options'=>['news'=>'News','press'=>'Press','event'=>'Event']],
                ['name'=>'summary','label'=>'Summary','type'=>'textarea'],
                ['name'=>'content','label'=>'Content','type'=>'textarea'],
                ['name'=>'image','label'=>'Image','type'=>'image'],
                ['name'=>'published_at','label'=>'Publish Date','type'=>'date'],
                ['name'=>'status','label'=>'Status','type'=>'select','options'=>['draft'=>'Draft','published'=>'Published']],
            ],
        ],
        'awards' => [
            'label' => 'Awards', 'table' => 'awards', 'permission' => 'content.manage',
            'title_field' => 'title', 'order' => 'position, id', 'search' => ['title'],
            'columns' => ['title', 'organisation', 'award_year', 'is_active'],
            'fields' => [
                ['name'=>'title','label'=>'Award Title','type'=>'text','required'=>true],
                ['name'=>'organisation','label'=>'Organisation','type'=>'text'],
                ['name'=>'award_year','label'=>'Year','type'=>'text'],
                ['name'=>'description','label'=>'Description','type'=>'textarea'],
                ['name'=>'image','label'=>'Image','type'=>'image'],
                ['name'=>'is_active','label'=>'Active','type'=>'checkbox'],
                ['name'=>'position','label'=>'Display Order','type'=>'number'],
            ],
        ],
        'academics' => [
            'label' => 'Academics', 'table' => 'academics', 'permission' => 'content.manage',
            'title_field' => 'title', 'order' => 'event_date DESC, id DESC', 'search' => ['title'],
            'columns' => ['title', 'type', 'event_date', 'status'],
            'fields' => [
                ['name'=>'title','label'=>'Title','type'=>'text','required'=>true],
                ['name'=>'type','label'=>'Type (CME, Workshop, Fellowship...)','type'=>'text'],
                ['name'=>'description','label'=>'Description','type'=>'textarea'],
                ['name'=>'event_date','label'=>'Date','type'=>'date'],
                ['name'=>'image','label'=>'Image','type'=>'image'],
                ['name'=>'status','label'=>'Status','type'=>'select','options'=>['draft'=>'Draft','published'=>'Published']],
            ],
        ],
        'community' => [
            'label' => 'Community Initiatives', 'table' => 'community_initiatives', 'permission' => 'content.manage',
            'title_field' => 'title', 'order' => 'event_date DESC, id DESC', 'search' => ['title'],
            'columns' => ['title', 'event_date', 'status'],
            'fields' => [
                ['name'=>'title','label'=>'Title','type'=>'text','required'=>true],
                ['name'=>'description','label'=>'Description','type'=>'textarea'],
                ['name'=>'event_date','label'=>'Date','type'=>'date'],
                ['name'=>'image','label'=>'Image','type'=>'image'],
                ['name'=>'status','label'=>'Status','type'=>'select','options'=>['draft'=>'Draft','published'=>'Published']],
            ],
        ],
        'insurance' => [
            'label' => 'Insurance Partners', 'table' => 'insurance_partners', 'permission' => 'content.manage',
            'title_field' => 'name', 'order' => 'position, id', 'search' => ['name'],
            'columns' => ['name', 'is_active'],
            'fields' => [
                ['name'=>'name','label'=>'Insurer / TPA Name','type'=>'text','required'=>true],
                ['name'=>'logo','label'=>'Logo','type'=>'image'],
                ['name'=>'notes','label'=>'Notes','type'=>'text'],
                ['name'=>'is_active','label'=>'Active','type'=>'checkbox'],
                ['name'=>'position','label'=>'Display Order','type'=>'number'],
            ],
        ],
        'pages' => [
            'label' => 'Page Sections (Homepage / About)', 'table' => 'page_sections', 'permission' => 'content.manage',
            'title_field' => 'section_key', 'order' => 'page, position', 'search' => ['title', 'content', 'section_key'],
            'columns' => ['page', 'section_key', 'title', 'is_active'],
            'fields' => [
                ['name'=>'page','label'=>'Page','type'=>'select','options'=>['home'=>'Homepage','about'=>'About Us']],
                ['name'=>'section_key','label'=>'Section Key','type'=>'text','required'=>true],
                ['name'=>'title','label'=>'Title','type'=>'text'],
                ['name'=>'subtitle','label'=>'Subtitle','type'=>'text'],
                ['name'=>'content','label'=>'Content','type'=>'richtext'],
                ['name'=>'image','label'=>'Image','type'=>'image'],
                ['name'=>'position','label'=>'Display Order','type'=>'number'],
                ['name'=>'is_active','label'=>'Active','type'=>'checkbox'],
            ],
        ],
        'footer_links' => [
            'label' => 'Footer Links', 'table' => 'footer_links', 'permission' => 'settings.manage',
            'title_field' => 'label', 'order' => 'column_group, position', 'search' => ['label'],
            'columns' => ['column_group', 'label', 'url', 'is_active'],
            'fields' => [
                ['name'=>'column_group','label'=>'Column Group','type'=>'text','required'=>true],
                ['name'=>'label','label'=>'Label','type'=>'text','required'=>true],
                ['name'=>'url','label'=>'URL','type'=>'text','required'=>true],
                ['name'=>'position','label'=>'Display Order','type'=>'number'],
                ['name'=>'is_active','label'=>'Active','type'=>'checkbox'],
            ],
        ],
        'seo' => [
            'label' => 'SEO Manager', 'table' => 'seo_metadata', 'permission' => 'seo.manage',
            'title_field' => 'route', 'order' => 'route', 'search' => ['route', 'meta_title'],
            'columns' => ['route', 'meta_title', 'robots'],
            'fields' => [
                ['name'=>'route','label'=>'Route (e.g. /about-us)','type'=>'text','required'=>true],
                ['name'=>'meta_title','label'=>'Meta Title','type'=>'text'],
                ['name'=>'meta_description','label'=>'Meta Description','type'=>'textarea'],
                ['name'=>'canonical_url','label'=>'Canonical URL','type'=>'text'],
                ['name'=>'og_image','label'=>'Social Image URL','type'=>'text'],
                ['name'=>'robots','label'=>'Robots','type'=>'select','options'=>['index,follow'=>'index,follow','noindex,follow'=>'noindex,follow','noindex,nofollow'=>'noindex,nofollow']],
            ],
        ],
        'redirects' => [
            'label' => 'Redirect Manager', 'table' => 'redirects', 'permission' => 'seo.manage',
            'title_field' => 'old_url', 'order' => 'id DESC', 'search' => ['old_url', 'new_url'],
            'columns' => ['old_url', 'new_url', 'status_code', 'hits', 'is_active'],
            'fields' => [
                ['name'=>'old_url','label'=>'Old URL (e.g. /old-page)','type'=>'text','required'=>true],
                ['name'=>'new_url','label'=>'New URL','type'=>'text','required'=>true],
                ['name'=>'status_code','label'=>'Status Code','type'=>'select','options'=>['301'=>'301 Permanent','302'=>'302 Temporary']],
                ['name'=>'is_active','label'=>'Active','type'=>'checkbox'],
            ],
        ],
        'email_templates' => [
            'label' => 'Email Templates', 'table' => 'email_templates', 'permission' => 'settings.manage',
            'title_field' => 'template_key', 'order' => 'template_key', 'search' => ['template_key', 'subject'],
            'columns' => ['template_key', 'subject'],
            'fields' => [
                ['name'=>'template_key','label'=>'Template Key','type'=>'text','required'=>true],
                ['name'=>'subject','label'=>'Subject','type'=>'text','required'=>true],
                ['name'=>'body','label'=>'Body ({{placeholders}} supported)','type'=>'textarea','required'=>true],
            ],
        ],
    ];
}
